excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - "R.generated.swift"
  - Cryptoboy-iOS/R.generated.swift

opt_in_rules:
  - array_init
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - number_separator
  - operator_usage_whitespace
  - override_in_extension
  - overridden_super_call
  - pattern_matching_keywords
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - required_enum_case
  - sorted_first_last
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

trailing_comma:
  mandatory_comma: true

line_length: 180
force_cast: warning # implicitly

disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - line_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
#  - discarded_notification_center_observer
  - unused_closure_parameter
  - function_parameter_count

  - private_over_fileprivate
  - strict_fileprivate

  - multiple_closures_with_trailing_closure